analytics.account={"id"\:1685511,"name"\:"My Account_01","uuid"\:"80e50c61-88fb-4522-8dac-0f637bb312a7","domain"\:"ac-1685511"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3506136,"name"\:"Bajaj_2.0","teamId"\:3504547,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3500568,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3504547,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email=keerthikumar@wizzybox.com
onpremise.password=VJZQZosRXKjy9uXIC9LBvw\=\=
